[server]
maxUploadSize = 50
enableXsrfProtection = false

[runner]
magicEnabled = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
